# Este archivo le indica a Netlify cómo construir y desplegar el sitio.
# Es el plano maestro para nuestro equipo de construcción automático.

[build]
  # No hay un paso de construcción para este proyecto simple,
  # ya que es solo HTML y JS. Netlify servirá los archivos desde la raíz.
  # El directorio 'publish' se omite, Netlify usará la raíz por defecto.

[functions]
  # Directorio donde Netlify buscará las funciones serverless.
  # CADA archivo .js aquí se convierte en un endpoint de API.
  directory = "functions/"

